### ISSUE TITLE
Allow the algorithm to be ran from command line

### ISSUE THREAD

**Issue by thibauld** [algorun/algorun#14]
Today we allow the algorithm to be ran:
- from the web
- from a web api
  I think it would be good to complete this list by allowing the algorithm to be ran from command line. Even though it is not our target use case, this is what a lot of scientists are used to today. Plus, just the fact of abstracting all the dependencies is already a big plus from a scientist standpoint.

I thought we could leverage the `docker exec` command to achieve this by automatically creating a symlink in /bin/algorun that points to the algorithm main program.

Example usage : `$ docker exec -d <container_name> /bin/algorun < sample_input.txt`
https://docs.docker.com/reference/commandline/exec/

**Comment by abdelrahmanhosny** [comment]
When an algorithm developer prepares his algorithm to be run on algorun, he states that the output should go to an output file. If I created a symlink that points to the algorithm main program, how should we return the result  from the output file? 
That is; 
docker exec -d <container_name> /bin/algorun < sample_input.txt
executes his algorithm and put the result in output file, not returned immediately to the terminal.
Do you mean that I should create another wrapper (like the server) that takes the input, run the algorithm and outputs the result to the terminal? or you have another idea of implementing this?

Also,
We can add a documentation for using curl to POST a request as an additional way of using the algorithm.

**Comment by thibauld** [comment]
The idea I had in mind was indeed to create a (very small) wrapper that would forward the input to the main program and then read the resulting output file to return it.

Regarding curl, I agree we can add it as an example as how to test the web API. However it is not an additional way to use the algorithm as it is just a way to use (I would rather say "test") the web API.
