### ISSUE TITLE
Do not duplicate the declaration of variable in the Dockerfile and in the manifest.json

### ISSUE THREAD

**Issue by thibauld** [algorun/algorun#19]
I realized when you sent your email to Mitra that you were asking her to declare parameters both in the Dockerfile and in the manifest. This is not good because it does not make sense from a user standpoint. The user should not have to support the consequences of our programming constraints :)

Here is a proposal: 
What is we removed the declaration of the parameters from the Dockerfile and just put them in the manifest. I see several advantages:
1. No more duplication
2. We have more flexibility in the manifest.json file where we will be able to:
1. allow variables more complex than only numbers 
2. type variables so that we can check if the variable is of the right type when it is being modified by the user

What do you think ?

**Comment by abdelrahmanhosny** [comment]
I was implementing them previously to be declared in the Dockerfile only. But I think you have a good point regarding the manifest. I will change it the way you proposed.

**Comment by thibauld** [comment]
Thanks, and also, I just thought that it could be useful later on if we want to provide a little documentation (tooltip like) for each parameter.
