### ISSUE TITLE
Add multiple input/ouput support

### ISSUE THREAD

**Issue by thibauld** [algorun/algorun#20]
Some algorithms require multiple files as inputs (not just one) so it would be good to add support for multiple inputs in algorun,

**Comment by thibauld** [comment]
implementation proposal:
1. getting rid of "algo_input_stream" and "algo_output_stream" as well as "input_type" and "output_type"
2. Add "input" and "output"

``` json
input: [
{type:'json',content:'[custom:mydata,algorun:timeseries]',stream:'file'},
{type:'json',content:'[custom:mydata2,algorun:graph]',stream:'direct'},
]
```

and same idea with output.

**Comment by abdelrahmanhosny** [comment]
a modified proposal:
input: [
{type:'custom:mydata', stream:'direct'},
{type:'algorun:graph', stream:'file'},
]

**Comment by abdelrahmanhosny** [comment]
added in v2.0
