### ISSUE TITLE
add a /manifest method to the algorun api to retrieve the manifest.json file

### ISSUE THREAD

**Issue by thibauld** [algorun/algorun#24]
In order to submit an algorithm to algorun, the only thing needed should be the docker hub repository (ex: ahosny/react).

I will add a form on algorun.org for people to submit their algorithm this way.
Once we have the docker hub repository, we can automatically:
1. deploy the container locally
2. perform a few tests to verify it is a valid algorun container (check /run / config /manifest)
3. get the manifest.json (via /manifest) and use to register the container in the "yet-to-come" container database
4. update the nginx config to add <name>.algorun.org as the algorithm algorun url

**Comment by thibauld** [comment]
Unfortunately, it does not seem to work : `http://react.algorun.org/manifest` returns `Cannot GET /manifest`. 

Also, let's comply with #25 (sorry again) and make the manifest available at `/v1/manifest` instead of `/manifest`.

**Comment by abdelrahmanhosny** [comment]
I implemented it as POST to make all calls the same method. Do you think it would be better to make this one a GET?
Ok, I will version them.

**Comment by thibauld** [comment]
Yes, the general rule for consistency is to use POST when you want to actually push/upload/ information and GET when you just want to read information.
