### ISSUE TITLE
API and web interface refuse large input files

### ISSUE THREAD

**Issue by agdphd** [algorun/algorun#28]
If a large object is passed as input, the API returns a 413 "Request entity too large" error. I encountered this with an input file of just 396KB; I am sure that some use cases will require input files far larger than this.

**Comment by abdelrahmanhosny** [comment]
@agdphd 
Is it through the web user interface only or the web API too? I appreciate if you can upload a file as a test case.

**Comment by agdphd** [comment]
This occurs through both the in-browser interface and the API. (If you try it with the in-browser interface, the output window shows "An error occurred!" and the Docker container throws out a Node "request entity too large".)

I don't see any way to attach a file to this post, but I got the same error with a randomly-generated 512KB text file, which you can produce with the following:

```
base64 /dev/urandom | head -c 512K > testfile
```
