### ISSUE TITLE
PUSH to /run times out after 120s

### ISSUE THREAD

**Issue by agdphd** [algorun/algorun#29]
The PUSH API at /run times out and aborts the HTTP connection after 120s if the underlying algorithm code has not returned by then. Of course, some algorithms take longer than this to run on some inputs. If there must be a timeout, please make it very large by default and configurable; much better (for my purposes) would be to remove the timeout altogether.

**Comment by abdelrahmanhosny** [comment]
@agdphd 
I troubleshooted this and found it is not related to the server. The express nodejs server we are using never send a timeout, neither through the web UI nor using /run directly. If you are using /run, please make sure that the request you are sending sets the timeout properly on the client side. I believe that the client is the one that aborts the request after specified amount of time (in the method you used, it was 120 seconds).

**Comment by agdphd** [comment]
I see the same behavior in a new test container based on `sleep`. The pull request seems to fix the problem, though. Let me know if you want the container for testing purposes.

**Comment by thibauld** [comment]
I was not able to test the fix myself but the code made sense and given the the size of the PR (2 lines), it cannot do much harm. @abdelrahmanhosny could you please test to see if it solves the issue ? otherwise please reopen. Thanks!
