### ISSUE TITLE
Ubuntu base container lacks GCC5

### ISSUE THREAD

**Issue by agdphd** [algorun/algorun#32]
The shipping Algorun container offers the GCC-4.8.4 compiler suite; GCC-4.9.1 is also available from the Ubuntu repositories. However, the GCC-5 suite is not available in this release of Ubuntu at all. As a result, I have needed to re-roll the Algorun image on top of debian:latest to build C++ code that uses some new-fangled features only supported in the GCC-5 branch.

I'm not sure what the right way is for Algorun to address this, but I'm sure I won't be the last person to miss this package.

**Comment by abdelrahmanhosny** [comment]
@agdphd 
We have just up pushed images of Algorun that is based on latest version of ubuntu, which has GCC5.
You can change the FROM in the dockerfile to algorun/algorun:15.10 or algorun/algorun:15.04
Note that in the new images, the web api endpoints changed from /run to /v1/run and /config to /v1/config
