### ISSUE TITLE
API and web interface refuse large input files (redux)

### ISSUE THREAD

**Issue by agdphd** [algorun/algorun#33]
The fix for #28 handled medium-sized files (like the 512kB example discussed there). However, Algorun fails in a new way with very large files (such as a 500MB example I'm working with). In this case, the whole server application crashes with the following error message:

```
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
```

I did a bit of digging, and I think the problem is caused by having NodeJS store the input file in memory before writing it to disk (rather than streaming it through); this means that it can only handle files that fit in its maximum memory, which is not especially large.

Unfortunately, fixing this is beyond the scope of my (essentially non-existent) NodeJS knowledge.

**Comment by agdphd** [comment]
For reference, on my machine, a 16MB file did not trigger this problem but a 50MB file did.

**Comment by abdelrahmanhosny** [comment]
@agdphd 
Thank you Andrew for posting the issue. I will investigate on that and provide an update very soon.
