### ISSUE TITLE
Add the AlgoRun logo to the algorithm webpage

### ISSUE THREAD

**Issue by thibauld** [algorun/algorun#38]
We should add the logo:
- in the favion (as you did in the algorun.org website)
- at the bottom of the page (in the powered by)
- at the top left of the page (where the logo should be placed in the bootstrap template)

**Comment by abdelrahmanhosny** [comment]
@thibauld 
Isn't putting the logo at top left of the page too much of branding? Isn't the Powered by and favicon enough? I tried putting it, but I felt I'm in AlgoRun website not an algorithm page where our main focus is to credit the algorithm and authors; not algorun itself. In addition, most third-party tools out there just put "Powered by" (themes, Algolia, Wufoo, Disqus, ..etc.)
What do you think?

**Comment by thibauld** [comment]
If you think it is too much then I follow your advice. Let's not put it at the top left of the page then.
